In [1]:
#Create a numpy array filled with all ones by defining its shape.

import numpy as np

shape = (3, 4)
arr = np.ones(shape)
print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
#How do you remove rows from a Numpy array that contains non-numeric values?
import numpy as np

arr = np.array([
    ["1", "2", "3"],
    ["4", "five", "6"],
    ["7", "8", "9"],
    ["ten", "11", "12"]
])

def is_numeric_row(row):
    try:
        row.astype(float)
        return True
    except ValueError:
        return False

filtered = np.array([row for row in arr if is_numeric_row(row)], dtype=float)

print(filtered)


[[1. 2. 3.]
 [7. 8. 9.]]


In [3]:
#Remove single-dimensional entries from the shape of an array
import numpy as np

arr = np.array([[[1, 2, 3]]])  
print("Original shape:", arr.shape)

squeezed = np.squeeze(arr)
print("Squeezed shape:", squeezed.shape)
print(squeezed)


Original shape: (1, 1, 3)
Squeezed shape: (3,)
[1 2 3]


In [4]:
# How do you check whether specified values are present in the NumPy array?

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(20 in arr)      
print(25 in arr)      
values = [20, 25, 50]
result = np.isin(values, arr)
print(result)        


True
False
[ True False  True]


In [5]:
# Write a NumPy program to sort a given array of shape 2 along the first axis, last axis, and flattened array.

import numpy as np

arr = np.array([[12, 5, 7],
                [1, 9, 3]])

sorted_first_axis = np.sort(arr, axis=0)
sorted_last_axis = np.sort(arr, axis=-1)
sorted_flattened = np.sort(arr, axis=None)

print("Original array:\n", arr)
print("Sorted along first axis:\n", sorted_first_axis)
print("Sorted along last axis:\n", sorted_last_axis)
print("Sorted flattened array:\n", sorted_flattened)


Original array:
 [[12  5  7]
 [ 1  9  3]]
Sorted along first axis:
 [[ 1  5  3]
 [12  9  7]]
Sorted along last axis:
 [[ 5  7 12]
 [ 1  3  9]]
Sorted flattened array:
 [ 1  3  5  7  9 12]


In [6]:
# Write a NumPy program to create a structured array from a given student name, height, class, and data type. Now sort by class, then height if the classes are equal.

import numpy as np

data = np.array([
    ('James', 5.9, 10),
    ('Alice', 5.5, 9),
    ('Bob', 6.0, 10),
    ('Daisy', 5.7, 9)
], dtype=[('name', 'U10'), ('height', 'f4'), ('class', 'i4')])

sorted_data = np.sort(data, order=['class', 'height'])

print(sorted_data)


[('Alice', 5.5,  9) ('Daisy', 5.7,  9) ('James', 5.9, 10) ('Bob', 6. , 10)]


In [7]:
# Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

import numpy as np

arr = np.array([2+3j, 1+2j, 2+1j, 1+4j, 3+0j])

sorted_arr = np.array(sorted(arr, key=lambda x: (x.real, x.imag)))

print("Original array:", arr)
print("Sorted array:", sorted_arr)


Original array: [2.+3.j 1.+2.j 2.+1.j 1.+4.j 3.+0.j]
Sorted array: [1.+2.j 1.+4.j 2.+1.j 2.+3.j 3.+0.j]


In [8]:
# Write a NumPy program to sort a given array by the nth column.

import numpy as np

arr = np.array([[10, 2, 30],
                [4, 15, 6],
                [7, 8, 1],
                [3, 12, 9]])

n = 1
sorted_arr = arr[arr[:, n].argsort()]

print("Original array:\n", arr)
print(f"Array sorted by column {n}:\n", sorted_arr)


Original array:
 [[10  2 30]
 [ 4 15  6]
 [ 7  8  1]
 [ 3 12  9]]
Array sorted by column 1:
 [[10  2 30]
 [ 7  8  1]
 [ 3 12  9]
 [ 4 15  6]]


In [9]:
# Calculate the sum of the diagonal elements of a NumPy array

import numpy as np

arr = np.array([[5, 2, 3],
                [4, 6, 7],
                [8, 9, 1]])

diag_sum = np.trace(arr)

print("Array:\n", arr)
print("Sum of diagonal elements:", diag_sum)


Array:
 [[5 2 3]
 [4 6 7]
 [8 9 1]]
Sum of diagonal elements: 12


In [10]:
# Write a program for Matrix Multiplication in NumPy

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

result = np.matmul(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of Matrix Multiplication:\n", result)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result of Matrix Multiplication:
 [[ 58  64]
 [139 154]]
